// One explicitly illustrative home is shared by the comparison, 3D demo and walkthrough.
const wall = (id: number, x1: number, y1: number, x2: number, y2: number) => ({
  entityId: id,
  x1,
  y1,
  x2,
  y2,
  thickness: 0.18,
  heightM: 2.8,
});
const room = (
  id: string,
  name: string,
  x: number,
  y: number,
  w: number,
  h: number,
) => ({
  id,
  name,
  areaM2: w * h,
  perimeterM: 2 * (w + h),
  center: { x: x + w / 2, y: y + h / 2 },
  polygon: [
    { x, y },
    { x: x + w, y },
    { x: x + w, y: y + h },
    { x, y: y + h },
  ],
});
export const demoAnalysis = {
  scanStatus: "ready",
  ifcPlan: {
    walls: [
      wall(1, 0, 0, 12, 0),
      wall(2, 12, 0, 12, 10),
      wall(3, 12, 10, 0, 10),
      wall(4, 0, 10, 0, 0),
      wall(5, 0, 5, 12, 5),
      wall(6, 6, 0, 6, 10),
    ],
    openings: [
      {
        kind: "door",
        wallEntityId: 1,
        position: 0.27,
        widthM: 1.1,
        heightM: 2.2,
      },
      {
        kind: "door",
        wallEntityId: 5,
        position: 0.24,
        widthM: 1.1,
        heightM: 2.2,
      },
      {
        kind: "door",
        wallEntityId: 5,
        position: 0.73,
        widthM: 1.1,
        heightM: 2.2,
      },
      {
        kind: "door",
        wallEntityId: 6,
        position: 0.27,
        widthM: 1.1,
        heightM: 2.2,
      },
      {
        kind: "door",
        wallEntityId: 6,
        position: 0.73,
        widthM: 1.1,
        heightM: 2.2,
      },
      {
        kind: "window",
        wallEntityId: 2,
        position: 0.25,
        widthM: 2.2,
        heightM: 1.5,
      },
      {
        kind: "window",
        wallEntityId: 3,
        position: 0.3,
        widthM: 2.4,
        heightM: 1.5,
      },
      {
        kind: "window",
        wallEntityId: 4,
        position: 0.28,
        widthM: 2.4,
        heightM: 1.5,
      },
    ],
  },
  inferredRooms: [
    room("majlis", "المجلس", 0, 0, 6, 5),
    room("living", "الصالة", 6, 0, 6, 5),
    room("bedroom", "غرفة النوم", 0, 5, 6, 5),
    room("kitchen", "المطبخ", 6, 5, 6, 5),
  ],
};
const item = (
  category: string,
  name: string,
  room: string,
  x: number,
  y: number,
  w: number,
  d: number,
  h: number,
  color: string,
) => ({
  category,
  name,
  room,
  planX: (x / 12) * 1000,
  planY: ((10 - y) / 10) * 1000,
  widthM: w,
  depthM: d,
  heightM: h,
  rotationDeg: 0,
  color,
  material: "خامة توضيحية",
  details: "عنصر من المنزل التجريبي؛ لا يرتبط بمنتج للبيع.",
});
export const demoDesign = {
  design: {
    style: "معاصر سعودي",
    concept: "مساحات هادئة وخامات طبيعية.",
    roomFinishes: [],
    items: [
      item("sofa", "كنبة المجلس", "المجلس", 3, 1, 3.2, 1, 0.8, "#ddd4c5"),
      item("table", "طاولة المجلس", "المجلس", 3, 2.7, 1.5, 0.8, 0.4, "#c7b393"),
      item("sofa", "كنبة الصالة", "الصالة", 9, 1, 3.2, 1, 0.8, "#b8bea9"),
      item("table", "طاولة الصالة", "الصالة", 9, 2.7, 1.5, 0.8, 0.4, "#c7b393"),
      item("bed", "سرير", "غرفة النوم", 3, 8, 2, 2.2, 0.6, "#e3dace"),
      item("kitchen", "خزائن المطبخ", "المطبخ", 9, 9.3, 4, 0.6, 0.9, "#9b7c5c"),
      item("table", "جزيرة المطبخ", "المطبخ", 9, 7.3, 2.4, 1, 0.9, "#d7c9b7"),
    ],
    lighting: [],
    airConditioning: [],
  },
};
